version: "3.9"
services:
    app:
        build:
            args:
                APP_BASE_DIR: ${APP_BASE_DIR-.}
            context: ./
            dockerfile: Dockerfile
        image: app
        restart: unless-stopped
        volumes:
            - ${APP_BASE_DIR-.}:/app
        networks:
            - app-network
    web:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - '8081:8081'
        volumes:
            - ${APP_BASE_DIR-.}/public:/app/public
            - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
        networks:
            - app-network
    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: products
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network
volumes:
    pg-data:
        driver: local

networks:
    app-network:
        driver: bridge

